### ISSUE TITLE
usePublish does not work

### ISSUE THREAD

**Issue by nazariyv** [oceanprotocol/react#127]
Hi,

`usePublish` goes into an infinite loop here

![CleanShot 2020-09-29 at 01 09 52@2x](https://user-images.githubusercontent.com/13678461/94497958-bc6d7180-01f0-11eb-94ad-5f580ec848ba.png)

I have a suspicion that it is due to an incorrect usage of React hooks (they can only be used inside of functional components; I do not think an arrow function meets that requirement)

![CleanShot 2020-09-29 at 01 09 07@2x](https://user-images.githubusercontent.com/13678461/94498001-deff8a80-01f0-11eb-885c-13bfe7b9e3ea.png)

The code (react component) that I have used to come up with this error is in this [gist](https://gist.github.com/nazariyv/4fe09660d2714bdda98a1f80c8dc7e1e)

My expected solution would be to get rid of calling `useContext` outside of functional components

A weird point is that it fails on the line when you try to convert 1 ether to wei here. Which is very strange indeed. Let me know what you think

<img width="520" alt="CleanShot 2020-09-29 at 01 39 21@2x" src="https://user-images.githubusercontent.com/13678461/94499447-a1046580-01f4-11eb-98c2-bbc5b3290c4d.png">

In any case, why is this hardcoded?

**Comment by nazariyv** [comment]
as far as I can see `useOcean` hook gets exported at the bottom of the file whilst using a `useContext` hook itself. Problem is, in my view, `useOcean` is not a functional component, which forbids you from using `useContext` in there. And in theory, `import { useOcean } from '@oceanprotocol/react` should not work at all. You could argue that since `useOcean` is custom hook, we can use `useContext`. Thing is with hooks, they are more of a convention than a feature, and so the distinction between a js function (you are not allowed to use hooks in that) and a custom hook is not very clear. But what is certain is that you cannot use hooks to share **state**. Each call to the custom hook creates a completed new encapsulated state. You are using `{ useOcean }` precisely to get the state from the context. And this is certainly not correct. This is my suspicion for why `usePublish` does not work for me. Btw, there is a linter to avoid issues relating to hooks, here

https://www.npmjs.com/package/eslint-plugin-react-hooks

Also materials, relating to what I have just talked about, can be found here

https://reactjs.org/docs/hooks-overview.html

**Comment by nazariyv** [comment]
I can see you have the mentioned plugin. Curious to know about the culprit of the issue then. Thank you

**Comment by nazariyv** [comment]
after removing the try catch in usePublish - which was supressing the stack traces from popping up and making it hard to debug this code

<img width="906" alt="CleanShot 2020-09-29 at 12 05 52@2x" src="https://user-images.githubusercontent.com/13678461/94550990-8958cb80-024c-11eb-94c4-1a6440cbf1a0.png">

**Comment by kremalicious** [comment]
yes, publishing is broken because of recent updates to ocean-lib-js. We are working on it

**Comment by kremalicious** [comment]
`ocean-lib-js` v0.3.2 together with `react` v0.0.48 works again with publishing in our apps, could you try again with those please?
