### ISSUE TITLE
incorrect type initialization in OceanProvider.tsx

### ISSUE THREAD

**Issue by nazariyv** [oceanprotocol/react#128]
<img width="815" alt="CleanShot 2020-09-29 at 10 28 02@2x" src="https://user-images.githubusercontent.com/13678461/94540623-9242a080-023e-11eb-9d04-c62a0ebf1041.png">

`as` keyword in Typescript is used to "hack" the type. Correct usage is the following

```
const OceanContext = createContext<OceanProviderValue>({
    web3: null,
    ...otherProps on OceanProviderValue
});
```

and just being a bit pedantic, I would rename the type to something like `OceanContextType`

Moreover, the conventional way to go about initiating the context is to have "default values"

for example,

```
export const DefaultOceanContextValues = {
    web3: null,
    accountId: "",
    someMethod: async () => Promise.reject(new Error('method unimplemented')),
};

export const OceanContext = createContext<OceanContextType>(
    DefaultOceanContextValues,
);
```

and this will be much cleaner than the current code

**Comment by nazariyv** [comment]
it would be interesting to know why interfaces are used instead of types, as well

https://stackoverflow.com/questions/37233735/typescript-interfaces-vs-types

even though the two are pretty much equivalent (except for declaration merging), the preference is usually to use type since it is syntactically more concise

**Comment by nazariyv** [comment]
I have re-wrote this without the useOcean hook in my repo but this has not solved the issue

**Comment by mihaisc** [comment]
Please make separate issues, don't stack multiple issues. 
1st issue : valid point, we'll look into it when we have time for refactoring
2nd issue: there were some changes in the backend and thus some updates were required in ocean-lib-js and in consequence in this lib too. New versions have been release for both, should work now.
