### ISSUE TITLE
Decouple web3/web3modal from OceanProvider

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/react#228]
Moving forward we need to get the react hooks more flexible for wallets usage.

Most flexible solution seems to be reducing the scope of `OceanProvider` to handle only Ocean connections, where it's assumed web3 is handled outside of it in the app.

_tbd or just some prototyping..._

High priority because it helps with multi-chain deployment

**Comment by mihaisc** [comment]
After multiple talks these are the main points to cover :

- [ ]  Decouple web3Provider  (web3Modal) from the `OceanProvider` . Basically this repo will just handle the creation of a ocean object and the rest of the hooks. The web3Provider will be handled in the main app ( market in our case)
- [ ] Create a separate repo for the example and fix it
- [ ]  Update readme
