### ISSUE TITLE
component: Versions

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/react#3]
Make `ocean.versions.get()` useful in some component with no or minimal styling.

Something which makes creating this in a frontend more easy:

<img width="780" alt="Screen Shot 2020-04-29 at 14 49 10" src="https://user-images.githubusercontent.com/90316/80598668-feb83a00-8a29-11ea-98f0-72af3ff11d03.png">

https://commons.oceanprotocol.com/about

**Comment by mihaisc** [comment]
if we do something like this, it should be in the market, not here
