### ISSUE TITLE
Handle logout

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/react#67]
We should provide those 2 use cases:

1. Switch wallet

When clicking _Switch Wallet_ the web3modal wallet selection should open, but the cached provider should not be cleared yet. Because user might close the modal without selection and in that case everything should stay as before. When user clicks on a wallet provider, do the connection and make sure the cached provider is replaced.

Right now in `market`, we fire `logout()` when user clicks _Switch Wallet_, which immediately clears the cached provider.

2. Exit

We should have some _Exit_ action, where when user clicks it, everything is cleared. This probably means setting the `OceanProvider` values to their initial state and clearing the cached provider.

https://github.com/oceanprotocol/react/blob/bccff55abe7b1ae8b504cedc0e06ae08b73ed031/src/providers/OceanProvider/OceanProvider.tsx#L126-L126

**Comment by alexcos20** [comment]
linked to https://github.com/oceanprotocol/market/pull/293

**Comment by mihaisc** [comment]
Already handled in market
