### ISSUE TITLE
Refetch balance

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/react#68]
Refetch balance periodically, or figure out some event to subscribe to. Right now, users have to reload the app to get an updated balance after the initial balance fetch.

https://github.com/oceanprotocol/react/blob/bccff55abe7b1ae8b504cedc0e06ae08b73ed031/src/providers/OceanProvider/OceanProvider.tsx#L153-L153

**Comment by mihaisc** [comment]
Hmm, i think i'll make a function and i'll call it on each major call ( publish, compute,consume, etc) .I don't think we have an event.

**Comment by kremalicious** [comment]
We might need it more often, especially with that new price widget where the balance is shown and connected to feedback so it kinda has to be almost live in there. So maybe `setInterval` with like 20 sec. is all we can do to get this

**Comment by mihaisc** [comment]
But does your wallet balance change that often? I mean, that is just a helper widget. In publish it's not an issue because i can check in publish if the balance is enough and give proper feedback. Other than that, how much can his balance change while browsing the website?

**Comment by kremalicious** [comment]
This is one of those things where yes, you don't need the balance to be correct all the time but when you need it, it's REALLY important. And for that really important use case there seems to be no other way than periodically refetching. The created overhead is outweighted by the usefulness when it's needed.

Imagine this user path we have:

1. user goes to `/publish`, starts filling out the form
2. arrives at price widget, then gets this:
   <img width="606" alt="Screen Shot 2020-08-03 at 18 24 49" src="https://user-images.githubusercontent.com/90316/89204590-a3608f80-d5b6-11ea-819c-3f7f24f7d63d.png">
3. user now sends OCEAN into the wallet, probably in another browser window/app
4. the user expectation now is that the balance in price widget updates itself, adding also that user will be hesitant to reload the page cause the form value saving is unknown to them

We could of course move the responsibility to the client, and expose a `fetchBalance()` method shit returns the same `balance` data structure, and then I could use it in selected places in the client to overwrite `balance` from the `OceanProvider`

**Comment by kremalicious** [comment]
That refetching a data source based on various user events is what SWR is actually perfect for, so it could be more than just a primitive `setInterval`: https://swr.vercel.app

**Comment by mihaisc** [comment]
one of SWR biggest advantage is the caching, that we clearly don't need. I'll add a fetchBalance method, but i'm not sure about adding a timer in the hooks.

**Comment by kremalicious** [comment]
So seems would be best to add an interval, like maybe 1 min. Or we use same mechanism we have for refreshing pools?

**Comment by mihaisc** [comment]
Yes i think that is better than adding an interval in the hooks, we shouldn't enforce the automatic refresh.

**Comment by ReangeloJ** [comment]
Did you guys check out react-query? That has automatic fetching capabillities and much more features which could be handy for the marketplace.

https://react-query.tanstack.com/docs/overview

**Comment by mihaisc** [comment]
Thanks for the suggestion, will look into it
